strictness: high
test-warnings: true
doc-warnings: false

ignore-paths:
  - tests
  - build
  - resources
  - .mypy_cache

pycodestyle:
  options:
    max-line-length: 100

pylint:
  disable:
    - super-init-not-called
    - unsubscriptable-object

mccabe:
  run: true
